Fix issue with deploying to k8s or openshift with etherpad
We get this erorr when deploying to kubernetes or openshift with the etherpad:
ERROR  :: - cli/main.py :: Unable to complete request: Status: 400,
Error: {u'status': u'Failure', u'kind': u'Status', u'code': 400,
u'apiVersion': u'v1', u'reason': u'BadRequest', u'message':
u'ReplicationController in version "v1" cannot be handled as a
ReplicationController: [pos 297]: json: expect char \'"\' but got char
\'3\'', u'metadata': {}}

This PR addes the quotes back and fixes the issue when deploying.